define Display 
	@echo "Entering Function "
    @echo " 0 is    $0"
	@echo " 1 is    $1"
    @echo " 2 is    $2"
	@echo " @ is    $@"
    @echo " Exit Function"
endef

x = Abdelhamid
target1:
	$(call Display,Rahma,$(x))
	@echo 
	@echo "Target is $@"


target2:
	@echo $(subst .c,.cpp, main.c test.c lcd.c)
	@echo $(patsubst %.c,%.o,x.c.c bar.c) 
	@echo $(sort zoo bar lose)
	@echo $(word 3, foo bar baz)
	@echo $(wordlist 2, 3, foo bar baz)
	@echo $(firstword foo bar)
	@echo $(lastword foo bar)

# file := test.c 
# build: clean
# 	@gcc $(file) -o runprogram

# clean:
# 	@rm *.o
# 	@rm runprogram